name: Create Pull Request on Branch Push

on:
  push:
    branches-ignore:
      - staging
      - launchpad
      - production

jobs:
  auto-pull-request:
    name: PullRequestAction

    runs-on: ubuntu-latest

    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          BRANCH_PREFIX: "feature/"
          PULL_REQUEST_BRANCH: "master"
