name: Eslint

on: [push]

jobs:
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: yarn lint
