name: GitHub Actions Node.js

on: [push, pull_request]

jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Run lint
        run: |
          yarn
          yarn format
