name: Test

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        #          MYSQL_DATABASE: facebook_tests
        #          MYSQL_HOST: 127.0.0.1
        #          MYSQL_USER: mysqladmin
        #          #          MYSQL_PASSWORD: root
        #          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        #          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: mysql
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword < etc/original.sql
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"
      - name: Execute test
        run: yarn test -t "by first name - the user who logged in, be first in the array"
