name: Test Coverage

on: [push]

jobs:
  tests-coverage:
    runs-on: ubuntu-latest
    env:
      name: env.test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Run test:coverage
        run: yarn test:coverage
