name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
#    env:
#      name: env.test
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: facebook_clone
          MYSQL_HOST: locahost
          MYSQL_USER: ortalyad
          ports:
            - 3306
          options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - name: Install dependencies
        run: yarn
      - name: Copy .env
        run: cp .env
      - name: Connect to Mysql
        run: |
          sudo service mysql start
          mysql -u ortalyad -p
          yarn migration:run
      - name: Run test
        run: yarn test
