name: Test

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: facebook_tests
          MYSQL_HOST: localhost
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Execute test
        run: |
          mysql --host localhost -uroot -e "SHOW DATABASES"
          yarn test -t "by first name - the user who logged in, be first in the array"
