name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: facebook_tests
          MYSQL_HOST: locahost
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Run test
        run: yarn test
