name: Test

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: facebook_tests
          MYSQL_USER: mysql_user
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD:
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Execute test
        run: yarn test
        env:
          DB_HOST: mysql

