name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      name: env.test
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: mirromutth/mysql-action@v1.1
      - name: Install dependencies
        run: yarn
      - name: build
        run: |
          sudo service mysql start
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot  < etc/original.sql
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -e "SHOW DATABASES"
          #This command adds the proper mysql port to the config file
          node scripts/ci ${{ job.services.mysql.ports['3306'] }}
      - name: Run test
        run: yarn test
