name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: facebook_tests
          MYSQL_HOST: locahost
          MYSQL_USER: 'ortalyad'
    steps:
      - uses: actions/checkout@v2
#        run: sudo service mysql stop
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Set up MySQL latest
      - name: Install dependencies
        run: yarn
      - name: Yarn migrations
        run: yarn migration:run
      - name: Run test
        run: yarn test
